lets make the link clickable
GeyserMC/GeyserWiki pull request #111
Opened 2023-01-08 18:30 UTC by onebeastchris

title

2023-01-08 19:04 UTC, Jens-Co approved these changes

2023-01-08 19:11 UTC, EasyClifton commented
Do you think just link.geysermc.org as the text (and clickable link) would look better? IMO it would.

2023-01-08 20:07 UTC, Chew requested changes
I'm with @EasyClifton, if you're gonna change the link text, reword the message to make it flow better

2023-01-08 20:28 UTC, onebeastchris commented
Fair point - ill just make the link clickable then, seems like the easiest/best seen solution

2023-01-28 01:06 UTC, rtm516 approved these changes

2023-01-28 01:07 UTC, merged