Update providers.json
GeyserMC/GeyserWiki pull request #116
Opened 2023-01-23 16:10 UTC by AgentDeath253

Updated falixnodes

2023-01-23 16:14 UTC, onebeastchris requested changes
Maybe it would be worth it to instead say "change the 'port' under the 'bedrock' section", as there are 2 port entries in the config.
Also,  punctuation at the end of the sentence wouldn't hurt

2023-01-24 01:33 UTC, AgentDeath253 commented
> Maybe it would be worth it to instead say "change the 'port' under the 'bedrock' section", as there are 2 port entries in the config. Also, punctuation at the end of the sentence wouldn't hurt
> 
> Also, "Geyser" with a capital "G"

better?

2023-01-24 09:08 UTC, onebeastchris commented
Yea, although 'Geyser MC Configuration' sounds a bit.. odd
maybe just "in the Geyser config."?

2023-01-24 17:26 UTC, onebeastchris commented
thanks, that's better

sorry if i'm annoying, but please do add a "." at the end of the last sentence - other than that, this looks good. Also, do users need to specify whether the port is for UDP/TCP?

2023-01-24 17:28 UTC, AgentDeath253 commented
do users need to specify whether the port is for UDP/TCP?

no they do not need to specify if the port is UDP/TCP

2023-01-24 17:30 UTC, onebeastchris approved these changes

2023-01-28 01:01 UTC, rtm516 requested changes

2023-01-28 01:01 UTC, rtm516 commented on _data/providers.json
> +      "description": "Get Geyser as a plugin. Open a port yourself on the network page in the game panel, then  change the port under the bedrock section of the Geyser config."
```suggestion
      "description": "Get Geyser as a plugin. Open a port yourself on the network page in the game panel, then change the port under the bedrock section of the Geyser config."
```

2023-02-15 01:08 UTC, onebeastchris approved these changes

2023-02-22 09:01 UTC, rtm516 approved these changes

2023-02-22 09:02 UTC, merged