Add development environment setup in the readme
GeyserMC/GeyserWiki pull request #167
Opened 2023-06-26 12:41 UTC by Jens-Co

2023-06-26 13:21 UTC, onebeastchris requested changes
added some suggestions about how i'd phrase it. Also, might be worth removing layout/permalink from the "example page layout section" since that'd outdated

2023-06-26 13:21 UTC, onebeastchris commented on README.md
> +### GeyserWiki  development setup locally
```suggestion
### GeyserWiki development - Local deployment 
```
double space; mayyybe better title? not fully sure about it tbh

2023-06-26 13:21 UTC, onebeastchris commented on README.md
> +* Download Ruby and Take the Ruby+Devkit from this page; https://rubyinstaller.org/downloads/
```suggestion
* Download and install Ruby using the Ruby+Devkit from https://rubyinstaller.org/downloads/.
```

2023-06-26 13:21 UTC, onebeastchris commented on README.md
> +* Once installed you will have to Run 'ridk install', this will open the RubyInstaller console.
```suggestion
* Once installed, run 'ridk install' in console to open the RubyInstaller.
```

2023-06-26 13:21 UTC, onebeastchris commented on README.md
> +Recommend choosing option 3; MSYS and MINGW after that ruby has been installed.
```suggestion
For this usecase, it is recommended to choose the third option, "MSYS and MINGW". After that, the Ruby installation is completed.
```
i'd mention that it's best for this usecase

2023-06-26 13:21 UTC, onebeastchris commented on README.md
> +* Once installed you can now start the server locally with command 'bundle exec jekyll serve'
```suggestion
* Once installed, you can start the webserver locally with the 'bundle exec jekyll serve' command in the VSC terminal. 
```

2023-06-26 20:24 UTC, Chew commented
This should go in a CONTRIBUTING.md file tbh. No need for it to be in the README.

2023-06-26 20:50 UTC, onebeastchris commented
@Chew if this should go into contributing.md, then the example should also be moved - imo, as this repo is only used to contribute, having a "contributing" section with all necessary details in the readme is enough.
But okay, if we move it, then we should move all of it - although that would leave a readme with basically just a description

2023-06-27 19:55 UTC, Chew commented
> if this should go into contributing.md, then the example should also be moved

Correct.

> imo, as this repo is only used to contribute, having a "contributing" section with all necessary details in the readme is enough.

If that's the case then Geyser's main repo README should have contributing stuff there too, right? The point of a README is to tell people passing by what the point of this repo is. Sure it's just a wiki repo. We could do a Contributing section that says "If you wanna contribute see our guidelines." This is just normal practice in repos tho, especially since GitHub handles CONTRIBUTING.md files better, by telling people who are making PRs about it and the etc.

> But okay, if we move it, then we should move all of it - although that would leave a readme with basically just a description

So be it, READMEs don't need to be overly descriptive.

2023-07-11 09:11 UTC, Tim203 commented
Is it an idea to provide a docker-compose file instead? I don't think everyone has Ruby e.g. but it's quite more likely that they have Docker installed.

2023-07-11 09:29 UTC, onebeastchris commented
personally, I found ruby simpler - I don't have docker set up atm
Maybe both would be an idea?

2023-07-17 16:57 UTC, rtm516 commented
> Is it an idea to provide a docker-compose file instead? I don't think everyone has Ruby e.g. but it's quite more likely that they have Docker installed.

On linux yes, docker would be better. But windows the ruby installer would be better.

I think this should be in `CONTRIBUTING.md` and split into setup for windows (ruby installer), linux (apt), docker and then having the shared things like `bundle install` in a section at the bottom.

2023-08-10 22:27 UTC, onebeastchris requested changes

2023-08-10 22:27 UTC, onebeastchris commented on CONTRIBUTING.md
> +page_sidebar: false "optional"
i would put optional in brackets here, but that might be just me

2023-08-10 22:27 UTC, onebeastchris commented on CONTRIBUTING.md
> +Most documentation is in the docs folder where you can add new page's or edit the current ones.
```suggestion
Most documentation is in the docs folder where you can add new pages or edit the current ones.
```

2023-08-10 22:27 UTC, onebeastchris commented on CONTRIBUTING.md
> +Make sure that the file extension is .md in this case pagetitle.md
```suggestion
Make sure that the file extension is .md - in this case `pagetitle.md`.
```

2023-08-10 22:27 UTC, onebeastchris commented on CONTRIBUTING.md
> +Once you have added the file you can add an sidebar link, All sidebar links + sub links are in the _data/toc.yml file
```suggestion
Once you have added the file you can add a sidebar link. All sidebar links + sub links are in the _data/toc.yml file.
```

2023-08-10 22:43 UTC, onebeastchris approved these changes

2023-08-24 20:01 UTC, onebeastchris approved these changes
After these, LGTM

2023-08-24 20:01 UTC, onebeastchris commented on CONTRIBUTING.md
> +### Adding page to sidebar
```suggestion
### Adding page to the sidebar 
```

2023-11-02 07:28 UTC, onebeastchris approved these changes
thanks :)

2023-11-02 07:29 UTC, merged