Update providers.json - Arth Hosting
GeyserMC/GeyserWiki pull request #262
Opened 2024-04-09 21:47 UTC by DiamonC

I added arth hosting and re-ordered apex hosting and aternos to be in alphabetical order

2024-04-12 12:16 UTC, rtm516 requested changes

2024-04-12 12:16 UTC, rtm516 commented on _data/providers.json
> +        {
```suggestion
    {
```

2024-05-06 21:20 UTC, onebeastchris approved these changes

2024-05-14 11:24 UTC, rtm516 approved these changes

2024-05-14 11:24 UTC, merged