Add advisory regarding OVH Game DDoS incompatibility
GeyserMC/GeyserWiki pull request #273
Opened 2024-05-10 08:53 UTC by ssh-sysadmin

Title. 

If and when OVH resolves this, the advisory can and should be removed as the use of the `minecraftPocketEdition` is advisable over the more permissive `Other` filter.

Related/relevant:
https://github.com/ovh/infrastructure-roadmap/issues/186
https://github.com/GeyserMC/Geyser/pull/4554

2024-05-10 19:42 UTC, onebeastchris requested changes

2024-05-10 19:42 UTC, onebeastchris commented on _docs/geyser/port-forwarding.md
> +The `minecraftPocketEdition` rule/filter/game type currently does not work and you must use the `Other` type.
This sounds a bit unclear - since this only applies to the "GAME" firewall

2024-05-10 19:42 UTC, onebeastchris commented on _docs/geyser/port-forwarding.md
> +If you would like to continue using `minecraftPocketEdition`, you may disable the incompatible security feature by adding `-DGeyser.RakSendCookie=false` to your startup flags for Geyser (works regard
```suggestion
If you would like to continue using the filter type `minecraftPocketEdition`, you may disable the incompatible security feature by adding `-DGeyser.RakSendCookie=false` to your Java server's (or Geyser Standalone proxy's) startup flags.
```

2024-05-12 12:01 UTC, rtm516 requested changes

2024-05-12 12:01 UTC, rtm516 commented on _docs/geyser/port-forwarding.md
> +    [The pull request which implemented the security feature that caused the incompatibility](https://github.com/GeyserMC/Geyser/pull/4554)
```suggestion
 - [This issue on OVH's infrastructure roadmap](https://github.com/ovh/infrastructure-roadmap/issues/186)  
 - [The pull request which implemented the security feature that caused the incompatibility](https://github.com/GeyserMC/Geyser/pull/4554)
```

2024-05-13 14:46 UTC, onebeastchris approved these changes

2024-05-14 11:25 UTC, rtm516 approved these changes

2024-05-14 11:26 UTC, merged