Update providers.json
GeyserMC/GeyserWiki pull request #274
Opened 2024-05-24 11:53 UTC by Vetta1337

Added Wepwawet host.

2024-05-24 15:07 UTC, onebeastchris requested changes

2024-05-24 15:07 UTC, onebeastchris commented on _data/providers.json
>      }
this list is in alphabetical order, please move your host to the correct spot

2024-05-27 05:33 UTC, onebeastchris approved these changes

2024-05-27 12:00 UTC, rtm516 approved these changes

2024-05-27 12:00 UTC, merged