Add the 2 alternate options for console connecting to the list
GeyserMC/GeyserWiki pull request #66
Opened 2022-07-09 01:49 UTC by Erisfiregamer1

Decided to add these, so people who just want to play their friend's server on console can do that a bit easier. No more DNS hijacking!

2022-10-24 10:46 UTC, GeekCornerGH requested changes

2022-10-24 10:46 UTC, GeekCornerGH commented on _docs/geyser/using-geyser-with-consoles.md
> +There is also a tool anyone can set up that allows you to connect to the server via adding a user to your friends list, as well as a tool admins can set up that allows connecting from a linked accoun
```suggestion
There is also a tool anyone can set up that allows you to connect to the server via adding a user to your friends list, as well as a tool admins can set up that allows connecting from a linked account of a user on the server. This tool can be found [here](https://github.com/rtm516/MCXboxBroadcast).
```

2022-10-30 12:35 UTC, Erisfiregamer1 commented on _docs/geyser/using-geyser-with-consoles.md
> +There is also a tool anyone can set up that allows you to connect to the server via adding a user to your friends list, as well as a tool admins can set up that allows connecting from a linked accoun
Damn, they deleted the repo :(

2022-11-01 09:19 UTC, GeekCornerGH approved these changes

2022-11-24 22:25 UTC, Tim203 approved these changes

2022-11-24 22:25 UTC, merged