Update anticheat-compatibility.md
GeyserMC/GeyserWiki pull request #70
Opened 2022-07-25 14:59 UTC by Filocava99

Add Cava's Anti Cheat to the list

2022-07-28 07:39 UTC, hasankayra04 approved these changes

2022-07-28 08:41 UTC, rtm516 requested changes

2022-07-28 08:41 UTC, rtm516 commented on _docs/geyser/anticheat-compatibility.md
> +- [Cava's Anti Cheat](https://www.spigotmc.org/resources/cavas-anti-cheat.102867/){:target="_blank"} - Last Updated on 21th July 2022
```suggestion
- [Cava's Anti Cheat](https://www.spigotmc.org/resources/102867/){:target="_blank"} - Last Updated on 21th July 2022
```

2022-08-02 09:45 UTC, Filocava99 commented
@rtm516 I have applied the requested changes

2023-09-07 10:49 UTC, rtm516 commented
This looks like a server+client anticheat, are we sure it will even accept Geyser players?

2023-09-07 19:20 UTC, Filocava99 commented
> This looks like a server+client anticheat, are we sure it will even accept Geyser players?

It does, already been tested by many players. Anyway I am currently not maintaining it anymore so do as you wish

2023-11-02 07:05 UTC, onebeastchris commented
I'm not sure we want to include unmaintained anticheats on the list - sorry.

2023-11-02 07:05 UTC, closed without merging