Update common-issues.md
GeyserMC/GeyserWiki pull request #80
Opened 2022-08-25 00:26 UTC by Jacold

Add info about IPv6 causing extreme lags when server don't support or isn't configured to handle IPv6 addresses.
https://github.com/GeyserMC/Geyser/issues/3207

2022-08-25 00:40 UTC, Camotoy commented
I'm unaware of what APN is.

2022-08-25 02:21 UTC, Jens-Co commented
I assume access point name. You should change APN to its full name, Otherwise it doesn't make much sense.

2022-08-25 14:20 UTC, Jacold commented
^ done

2023-09-07 10:51 UTC, rtm516 requested changes

2023-09-07 10:51 UTC, rtm516 commented on _docs/geyser/common-issues.md
> +Check your Access Point Name (APN) - if you're using IPv6 and server don't support or isn't configured to handle IPv6 addresses you need to change APN to IPv4.
```suggestion
Check your Access Point Name (APN) - if you're using IPv6 and the server doesn't support or isn't configured to handle IPv6 connections/addresses you need to change APN to IPv4.
```

2023-11-02 07:07 UTC, onebeastchris approved these changes
While niche, could be important. lgtm

2024-07-21 20:36 UTC, Chew commented
Hey there! Thank you for contributing to the wiki. We've migrated the wiki to our new [GeyserMC/GeyserWebsite](https://github.com/geysermc/geyserwebsite). If you'd like to, please migrate your PR to the new repo. From there, we can review it. Thank you for your contributions!

2024-07-21 20:36 UTC, closed without merging